import Head from "next/head";
import LoginForm from "~/components/loginForm/loginForm";

export default function Home() {
  return (
    <>
      <Head>
        <title>Grower Buddy</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-[#26343b]	">
        <LoginForm />
      </main>
    </>
  );
}
