import Head from "next/head";
import LoginSignupForm from "~/components/login-signup-form/LoginSignupForm";

export default function Home() {
  return (
    <>
      <Head>
        <title>Grower Buddy</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="min-w-screen flex min-h-screen flex-col items-center justify-center bg-[#26343b]">
        <LoginSignupForm />
      </main>
    </>
  );
}
